---
apiVersion: v1
kind: Secret
metadata:
  name: banking-secret

type: Opaque
stringData:
  POSTGRES_USER: "Enter your Postgres username"
  POSTGRES_PASSWORD: "Enter your Postgres Password"
  POSTGRES_DB: "Enter your own database name"
